### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by teri934** [stuchly/tviblindi#1]
Hi,

I wanted to install your package on my windows machine using `devtools::install_github("stuchly/tviblindi")`, but a fatal error occurred. Could you help me with that?

<img width="860" alt="image" src="https://user-images.githubusercontent.com/56218654/223489393-3f5272e3-43cb-4cbd-9f94-06c91d85d1fd.png">

**Comment by exaexa** [comment]
Hi all,
I'm adding myself to the list, got a similar problem (not identical though) while installing on linux: 
```
[...]
      |                      remove_cv
/usr/include/CGAL/Lazy.h:1310:22: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
 1310 |   Lazy_exact_nt<std::remove_cv_t<std::remove_reference_t<decltype(ec(CGAL::exact(l)...))>>>
      |                      ^~~~~~~~~~~
      |                      remove_cv
/usr/include/CGAL/Lazy.h:1310:39: error: ‘remove_reference_t’ is not a member of ‘std’; did you mean ‘remove_re`?
[...]
```

In the meantime it seems feasible to use docker (although vaevictis doesn't seem to work).

**Comment by stuchly** [comment]
Hi all,
I am sorry for late response. For some reason I am not being informed about new issues.

For the windows installation issue: Windows is not a supported platform at this moment, I recommend the use of the docker container. I will try to revisit this issue in the next couple months. 

For the linux installation: This issue most likely results from the legacy version of CGAL (version 4) which is currently used in tviblindi. Tviblindi would not compile when version 5 is installed. I intend to solve it ASAP (it is not as simple as I expected).

However vaevictis should work in the docker container, could you elaborate on this issue.

**Comment by exaexa** [comment]
Hi! In the end we managed with docker. I see the CGAL version requirement now; it might be nice to mark it as "explicitly not 5" because people (like me) tend to assume that if 4.14 is required, 5 would be OK. Other than that it seems to compile OK for me with cgal4, so I guess this is solved. Thanks a lot!

**Comment by stuchly** [comment]
Thank you for the suggestion - I updated readme accordingly
